language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t multi-docker/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multi-docker/client npm run test

after_success:
  - docker build -t bopagec/multi-client ./client
  - docker build -t bopagec/multi-nginx ./nginx
  - docker build -t bopagec/multi-server ./server
  - docker build -t bopagec/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker-hub
  - docker push bopagec/multi-client
  - docker push bopagec/multi-nginx
  - docker push bopagec/multi-server
  - docker push bopagec/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-762515311988
  bucket_path: docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET